### ISSUE TITLE
Game entries don't use any form of identifiers

### ISSUE THREAD

**Issue by liamdawson** [game-curator/game-curator#4]
Without this, there's no way to tie to BGG entries. Best approach is probably to put this data into a DB and query across that.

* [ ] Use knex to connect to Postgresql
* [ ] Add code to import game entries into the DB (update or create entries from the `games` folder)
* [ ] Update view logic to use new game entry logic

**Comment by eamq** [comment]
:+1: for Postgres!

It may make things easier later to go with an ORM.  http://bookshelfjs.org/ looks like it's easy enough to pick up if you're already familiar with knex (full disclosure: I've never used either, but have some experience with SQLAlchemy, and can help with defining the models).

**Comment by liamdawson** [comment]
I'm mainly interested in trying knex to experiment with using a layer between a full blown ORM, and a direct SQL library. I'm thinking if it turns out to be too tedious, it'd be relatively simple to migrate to Bookshelf later.

**Comment by jgimbel** [comment]
[This App](http://bgg.theahstudios.com/collections/) will take your bgg username and lookups all your games, then allows you to filter them.  This idea intrigues me because it would batch pull in games with minimal effort from a user. This might be able to help #20. They use a [mongo/mongoose](https://github.com/thealah/bgg/blob/master/lib/collection.js) model system.

Now saying this I realize that becoming too dependent on BGG could become a limitation down the road. Notice they do not filter by difficulty, time, or have a description of the game.  Whether that is because they do not have the data, or just because their angular app is 300KBs with just the two filters they have IDK.
On the other hand, it would be nice to have a connection to BGG in our schema, so we can grab ratings, images, and such later.

**Comment by liamdawson** [comment]
Planning to put BGG metadata into version 3 or 4 of the metadata for documents---moving to a frontend-based approach means I'm kiboshing plans to use a DB behind the scenes. The remainder of the ideas attached to this issue will be discussed in the ongoing metadata work.
